[platformio]
default_envs = seeed_xiao_esp32s3, esp32dev

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
monitor_filters = log2file, time, default
extra_scripts = pre:load_env.py
platform_packages =
    espressif/toolchain-riscv32-esp @ file://C:/Users/asif.zaman/.platformio/packages/toolchain-riscv32-esp

lib_deps =
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    mikalhart/TinyGPSPlus@^1.0.3

[env:seeed_xiao_esp32s3]
board = seeed_xiao_esp32s3

[env:esp32dev]
board = esp32dev



