[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = log2file, time, default
extra_scripts = pre:load_env.py



lib_deps =
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    mikalhart/TinyGPSPlus@^1.0.3
